[package]
edition = '2021'
name = 'plexo'
version = '0.2.0'

[dependencies]
async-graphql = { version = "5.0.4", features = ["decimal", "chrono", "dataloader"] }
async-graphql-poem = { version = "5.0.4" }
async-trait = { version = "0.1.53" }
poem = { version = "1.3.29" }
# sea-orm = { version = "0.10.5", features = ["sqlx-postgres", "runtime-async-std-native-tls"] }
# tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.34" }
tracing-subscriber = { version = "0.3.11" }
lazy_static = { version = "1.4.0" }
quote = "1.0"
tokio-stream = "0.1.11"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres", "uuid" ] }
tokio = { version = "1.17.0", features = ["full"] }
dotenvy = "0.15.6"

[dev-dependencies]
serde_json = { version = '1.0.82' }

[workspace]
members = []

[lib]
proc-macro = true
