[package]
edition = '2021'
name = 'plexo'
version = '0.2.0'

[dependencies]
async-graphql = { version = "5.0.4", features = ["decimal", "chrono", "dataloader", "uuid"] }
async-graphql-poem = { version = "5.0.4" }
poem = { version = "1.3.50", features = ["cookie"] }
tracing = { version = "0.1.34" }
tracing-subscriber = { version = "0.3.11" }
lazy_static = { version = "1.4.0" }
tokio-stream = "0.1.11"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls" , "postgres", "uuid", "time", "json", "offline"] }
tokio = { version = "1.17.0", features = ["full"] }
dotenvy = "0.15.6"
chrono = "0.4.23"
serde = "1.0.152"
serde_json = "1.0.82"
oauth2 = { version = "4.3.0", features = ["reqwest"] }
reqwest = { version = "0.11.13", features = ["json"]}
jsonwebtoken = "8.2.0"

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[workspace]
members = []

# [lib]
# proc-macro = true
