[package]
edition = '2021'
name = 'plexo'
version = '0.2.0'

[dependencies]
async-graphql = { version = "5.0.4", features = ["decimal", "chrono", "dataloader", "uuid"] }
async-graphql-poem = { version = "5.0.4" }
async-trait = { version = "0.1.53" }
poem = { version = "1.3.29" }
# sea-orm = { version = "0.10.5", features = ["sqlx-postgres", "runtime-async-std-native-tls"] }
# tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.34" }
tracing-subscriber = { version = "0.3.11" }
lazy_static = { version = "1.4.0" }
quote = "1.0"
tokio-stream = "0.1.11"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres", "uuid", "time", "json"] }
tokio = { version = "1.17.0", features = ["full"] }
dotenvy = "0.15.6"
chrono = "0.4.23"
serde = "1.0.152"
serde_json = "1.0.82"
oauth2 = { version="4.3.0", features = ["reqwest"] }

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[workspace]
members = []

# [lib]
# proc-macro = true
