[package]
edition = '2021'
name = 'plexo'
version = '0.2.9'

[dependencies]
async-graphql = { version = "5.0.9", features = ["decimal", "chrono", "dataloader", "uuid"] }
async-graphql-poem = { version = "5.0.9" }
poem = { version = "1.3.55", features = ["cookie", "static-files"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }
lazy_static = { version = "1.4.0" }
tokio-stream = "0.1.14"
sqlx = { version = "0.6.3", features = [ "runtime-tokio-native-tls" , "postgres", "uuid", "time", "json", "offline"] }
tokio = { version = "1.28.2", features = ["full"] }
dotenvy = "0.15.7"
chrono = "0.4.25"
serde = "1.0.163"
serde_json = "1.0.96"
oauth2 = { version = "4.4.0", features = ["reqwest"] }
reqwest = { version = "0.11.18", features = ["json"]}
jsonwebtoken = "8.3.0"
async-trait = "0.1.68"
percent-encoding = "2.2.0"
mime = "0.3.17"
async-openai = "0.10.3"
cookie = "0.17.0"
thiserror = "1.0.40"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "macro-diagnostics"] }
argon2 = "0.5.0"


[workspace]
members = []

# [lib]
# proc-macro = true
