version: '3.7'
services:
  postgres:
      image: postgres:15.2
      restart: always
      environment: 
        - POSTGRES_USER=plexo
        - POSTGRES_PASSWORD=example
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        # copy the sql script to fill tables


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  plexo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://plexo:example@postgres:5432/plexo
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    ports:
      - 8080:8080