version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: plexo
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./migrations:/migrations
      - ./migrations:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  plexo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://plexo:example@postgres:5432/plexo
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    ports:
      - 8080:8080