name: "Build image and push to official docker registry"

on:
  push:
    branches:
      - main

jobs:
  build-push-registry:
    name: Build image and push to official docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: minskylab/plexo
          flavor: |
            latest=true
          tags: |
            type=sha,format=long,prefix=sha-
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/dev' }}
            type=raw,value=stable,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          push: true
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}
